server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sai-gon-development/microservices-with-spring-boot.git
          search-paths: internet-banking-concept-microservices/internet-banking-configuration
          default-label: main
