spring:
  application:
    name: internet-banking-service-registry

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8081/eureka
#     fetch-registry: false
#     register-with-eureka: false
  # server:
    # enableSelfPreservation: false
    # wait-time-in-ms-when-sync-empty: 0
    # enable-self-preservation: false