server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://richardvu.com:8081/eureka
      
spring:
  datasource:
    url: jdbc:postgresql://richardvu.com:5432/banking_core_service
    username: postgres
    password: postgres@12
  jpa:
    hibernate:
      ddl-auto: update

info:
  app:
    name: ${spring.application.name}