spring:
  ## GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        ## EXTERNAL SERVICE
        - id: internet-banking-external
          uri: lb://internet-banking-external
          predicates:
            - Path=/banking-external/**
          filters:
            - StripPrefix=1
            
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://richardvu.com:8081/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: richardvu.com
    prefer-ip-address: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG