server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_external_service
    username: postgres
    password: postgres@12
  jpa:
    hibernate:
      ddl-auto: update
