spring:
  security:
    oauth2:
      client:
        registration:
          oauth2-demo-thymeleaf-client:
            client-id: oauth2-keycloak-client-id
            client-secret: uHM8waivW03h95vtyYZXU6umemBSG7kD
            scope: openid, profile, roles
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/oauth2-keycloak
        provider:
          oauth2-demo-thymeleaf-client:
            issuer-uri: http://richardvu.com:8010/auth/realms/spring-security-oauth2-keycloak
server:
  port: '8080'
