spring:
  datasource:
    url: jdbc:mysql://richardvu.com:3306/banking_core_service
    username: root
    password: root@12
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}
