server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://richardvu.com:3306/banking_core_fund_transfer_service
    username: root
    password: root@12
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}
